# Generated by Django 4.2.3 on 2023-08-15 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_articulo_options_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('cuerpo', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='comentario',
            name='cuerpo',
            field=models.TextField(),
        ),
    ]
