# Generated by Django 4.2.3 on 2023-08-15 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_comentario_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='blog.articulo'),
            preserve_default=False,
        ),
    ]
