# Generated by Django 4.2.3 on 2023-08-15 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comentario_articulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='articulo',
        ),
    ]
