# Generated by Django 4.2.3 on 2023-08-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_remove_comentario_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='description',
            field=models.TextField(default='descripcion de prueba'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='url',
            field=models.URLField(default='url'),
            preserve_default=False,
        ),
    ]
