# Generated by Django 4.2.3 on 2023-08-24 00:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_articulo_cuerpo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
