# Generated by Django 4.2.3 on 2023-08-24 02:30

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_articulo_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comentario', to='blog.articulo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comentario',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='cuerpo',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
