# Generated by Django 4.2.3 on 2023-08-24 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_comentario_articulo_alter_comentario_cuerpo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='blog.articulo'),
        ),
    ]
