# Generated by Django 4.2.3 on 2023-08-24 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_alter_comentario_articulo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='articulo',
            new_name='comment',
        ),
    ]
