# Generated by Django 4.2.3 on 2023-08-31 14:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_articulo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='descripcion',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='avatar',
            name='link',
            field=models.URLField(null=True),
        ),
    ]
