# Generated by Django 4.2.3 on 2023-08-31 16:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_alter_avatar_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avatar',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
