# Generated by Django 4.2.3 on 2023-09-01 03:53

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_alter_avatar_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='descripcion',
            field=ckeditor.fields.RichTextField(default='descripcion de prueba'),
            preserve_default=False,
        ),
    ]
