# Generated by Django 4.2.3 on 2023-09-01 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_avatar_descripcion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
